version: '3.9'

services:
  web:
    build: .
    container_name: dsp_web
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app/
      - staticfiles:/app/static/
      - media:/app/media
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DEBUG: ${DEBUG}
      IP: ${IP}
      ADS: ${HOST_IP}
      HOST_PORT: ${HOST_PORT}
      TEAMS: ${TEAMS}
      
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: dsp_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}


  nginx:
    build: ./nginx
    container_name: dsp_nginx
    volumes:
      - staticfiles:/app/static/
      - media:/app/media/
    ports:
      - "$HOST_IP:80:80"
    environment:
      - HOST_IP=${HOST_IP}
    depends_on:
      - web

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ${DB_HOST_VOLUME_PATH}
      o: bind
  staticfiles:
    driver: local
  media:
    driver: local