# Generated by Django 4.1.6 on 2023-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_campaign_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='initial_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='config',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
