# Generated by Django 4.1.6 on 2023-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_config_initial_budget_alter_campaign_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='config',
            name='budget',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='config',
            name='initial_budget',
            field=models.FloatField(default=0),
        ),
    ]
